### ISSUE TITLE
Cannot build Unity project for HoloLens (UWP) 

### ISSUE THREAD

**Issue by ergo333** [Unity-Technologies/ROS-TCP-Connector#117]
Hi, I'm working on a simple Robotics project where I need to control a virtual robot (in Unity) through HoloLens.
I've created a simple test scene with the imported URDF model of the robot itself (Universal Robot UR5) and installed the library ROS-TCP-connector as suggested from the installation guide. 
Just for some tests, I've tried to import a simple JointState message. 

If I build the project for the PC architecture, no problems at all, but when I select the Universal Windows Platform from the build preferences of Unity, the editor launches the following error messages:

- `Assets\RosMessages\Sensor\msg\MJointState.cs(8,13): error CS0234: The type or namespace name 'Robotics' does not exist in the namespace 'Unity' (are you missing an assembly reference?)`
- `Assets\RosMessages\Sensor\msg\MJointState.cs(58,38): error CS0115: 'MJointState.SerializationStatements()': no suitable method found to override`
- `Assets\RosMessages\Sensor\msg\MJointState.cs(82,29): error CS0115: 'MJointState.Deserialize(byte[], int)': no suitable method found to override`
- `Assets\RosMessages\Sensor\msg\MJointState.cs(127,32): error CS0115: 'MJointState.ToString()': no suitable method found to override`

I'm quite new to Unity environment and I believe that this problem can be caused by some compiling options or preprocessing directives that I am not aware of. 

The environment in this study case is the following:
- Unity 2020.3.9f1
- Windows 10 (PC with Unity and ROS melodic installed)
- Microsoft HoloLens (target architecture)
- .NET 4.0 build option

**Comment by sdiao** [comment]
Hi @ergo333 , thanks for reaching out. We are currently looking into the issue. We will let you know as soon as we have an update. Thanks.

**Comment by sdiao** [comment]
May I know which version of ROS-TCP-connector and URDF importer are you using? We just released v0.4.0 in both packages yesterday. I would recommend upgrade to the v0.4.0 in main branch first. 
[URDF-Importer v0.4.0](https://github.com/Unity-Technologies/URDF-Importer/tree/v0.4.0)
[ROS-TCP-Connector](https://github.com/Unity-Technologies/ROS-TCP-Connector/tree/v0.4.0)

**Comment by sdiao** [comment]
Hi @ergo333 , you will need to select UWP as a supported platform in `Unity.Robotics.ROSTCPConnector.asmdef`. You should be able to make a few small changes to the package structure in order to resolve those compile errors and create a UWP build. Please see a step-by-step instruction [here](https://github.com/Unity-Technologies/Unity-Robotics-Hub/issues/215#issuecomment-832181800). Let me know if it helps. Thanks.

**Comment by ergo333** [comment]
I was already using the latest version of both URDF-Importer and ROS-TCP-Connector (v0.4.0), but I tried also with the previous two versions but the issue was the same. 

Thank you for your immediate response! 
IT WORKS! Now I can build correctly my Unity package for UWP - HoloLens! 👍🏻

**Comment by sdiao** [comment]
I am glad it works for you. Please feel free to reach out if you have any questions. I will close the issue now. Thanks.
