### ISSUE TITLE
"CONTRIBUTING.md" contains a dead link

### ISSUE THREAD

**Issue by P3TE** [Unity-Technologies/ROS-TCP-Connector#130]
In: CONTRIBUTING.md,
Under Section: Code style
The linked text 'Unity Coding package' redirects to:
https://docs.unity3d.com/Packages/com.unity.coding@0.1/manual/index.html
Which returns **"Sorry... that page seems to be missing!"**

- Branch 'main' & 'dev' both have this issue.

**Comment by LaurieCheers-unity** [comment]
Thanks; the com.unity.coding package is no longer available, so I'll remove this link.

**Comment by sdiao** [comment]
We have updated our doc in https://github.com/Unity-Technologies/ROS-TCP-Connector/pull/145. Close this issue now.
