### ISSUE TITLE
Retrieve topic message types

### ISSUE THREAD

**Issue by bryceikeda** [Unity-Technologies/ROS-TCP-Connector#141]
I see in the RosConnection script there is a function that retrieves the topic names from the server_endpoint. I was wondering if it would be possible to add a feature/function that also allows me to retrieve topic message types. Similarly, adding a way to get if they are subscribers or publishers.

**Comment by peifeng-unity** [comment]
Thanks for the request, @bryceikeda, I created an internal ticket AIRO-1005 for this feature. We will follow up and let you know.

**Comment by bryceikeda** [comment]
@peifeng-unity Thank you!

**Comment by LaurieCheers-unity** [comment]
Hi, in the new version 0.5.0 you can call the function ROSConnection.instance.GetTopicAndTypeList().
https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/f7f669f212423ff03817a2094f489547158a3852/com.unity.robotics.ros-tcp-connector/Runtime/TcpConnector/ROSConnection.cs#L193

**Comment by bryceikeda** [comment]
@LaurieCheers-unity Oh awesome. I had problems with v0.5.0 so I didn't see this function. Thank you for getting back to me.
