### ISSUE TITLE
Coordinate Frame Transformations in ENU Don't Match The Standard

### ISSUE THREAD

**Issue by P3TE** [Unity-Technologies/ROS-TCP-Connector#163]
**Describe the bug**

In Unity, to convert a vector from unity space RUF (Right, Up, Front) to ENU (East, North, Up), the following transformation is applied:
`public Vector3 ConvertFromRUF(Vector3 v) => new Vector3(v.x, v.z, v.y);`
This assumes that in Unity a positive x is East, a positive z is North and a positive y is up.
However, to convert a rotation from Unity space RUF (Right, Up, Forward) to ENU (East, North, Up), the following transformation is applied:
`public Quaternion ConvertFromRUF(Quaternion q) => new Quaternion(q.x, q.z, q.y, -q.w);`
This however assumes when in Unity, an identity rotation (When the forward vector is positive z (0, 0, 1)) would also be an identity rotation in ENU. 
This means that in Unity, when facing z forward or North, the orientation in ENU is also the identity.
However in ENU, when the rotation is identity, forward should be facing East, see:
_"In case of land vehicles like cars, tanks etc., which use the ENU-system (East-North-Up) as external reference (World frame), **the vehicle's (body's) positive y- or pitch axis always points to its left**"_

![](https://upload.wikimedia.org/wikipedia/commons/f/f5/RPY_angles_of_cars.png)
_Image from Wikipedia shows the zero point on the yaw to be East, rotating counter-clockwise_
- https://en.wikipedia.org/wiki/Axes_conventions#World_reference_frames_for_attitude_description

The problem seems to be that:
Unity geographic coordinates have `+x = East`, `+y = Up` and `+z = North`, but when converting geographic rotations offsets are not taken into account `0 = North` when it should be `0 = East` (In ENU terms).

We found this discrepancy to be an issue when using Unity to simulate IMU data (converted to ENU before publishing) which would then be fed into the [ROS robot_localization package](http://docs.ros.org/en/noetic/api/robot_localization/html/preparing_sensor_data.html#coordinate-frames-and-transforming-sensor-data). When doing this, we found that we would be pitching when the object was rolling in Unity and vise versa. The robot_localization link provided indicates that ENU should be used for all IMU data. Switching the conversion to FLU and re-framing our environment such that `-x = North`, `+y = Up` and `+z = East` corrected this discrepancy.

To correctly convert a rotation from Unity space to ENU, either:
1. Unity should be `-x = North`, `+y = Up` and `+z = East` and ENU transformations should be equivalent to FLU transformations. _(Note: This would probably break NED rotational transformations)_
**OR**
2. Unity should apply a yaw offset of 90 degrees when converting from Unity orientations to ENU orientations and vice versa.

Is there something else about the Unity implementation that I am missing?

**Some related links**
- [REP-103 Standard Units of Measure and Coordinate Conventions](https://www.ros.org/reps/rep-0103.html)
- [REP-105 Coordinate Frames for Mobile Platforms](https://www.ros.org/reps/rep-0105.html)
- [REP-145 Conventions for IMU Sensor Drivers](https://www.ros.org/reps/rep-0145.html)

**Comment by hyounesy** [comment]
Ticket: AIRO-1188

**Comment by peifeng-unity** [comment]
Thanks, @P3TE for reporting the issue. We have made [a PR](https://github.com/Unity-Technologies/ROS-TCP-Connector/pull/174) to fix it.

**Comment by P3TE** [comment]
Thanks.
Ah, so within Unity, the coordinate system we should be using is: `x=South`, `y=Up` and `z=East`.

**Comment by P3TE** [comment]
Hi, looking through the PR, I noticed that while this fixes ENU, NED will now be out be 90 degrees.
The problem is similar to the original, but essentially, a yaw of 0 (The identity quaternion) in NED corresponds to north.
However, in the PR, a Unity identity quaternion (z-forward direction) when converted to NED would also produce an identity quaternion which would be incorrect as z is recognised as the East direction.
See:
![](https://upload.wikimedia.org/wikipedia/commons/8/83/RPY_angles_of_ships.png)
_Image from Wikipedia shows the zero point on the yaw to be North rotating clockwise_
- https://en.wikipedia.org/wiki/Axes_conventions#World_reference_frames_for_attitude_description

**Comment by peifeng-unity** [comment]
Hi @P3TE, thank you for taking a look at the PR. I might misunderstand you, but it seems to me that the NED conversion in the PR (as shown below) put the z-axis in the "Down" direction (`-v.y`), which seems the same as the image you've shown. Please correct me if I made mistakes.

```
public Vector3 ConvertFromRUF(Vector3 v) => new Vector3(-v.x, v.z, -v.y);
```

**Comment by P3TE** [comment]
Hey @peifeng-unity,
The issue is only with rotations, the  of Vectors are fine.

The issue is that:
- In ENU, A Yaw of 0 degrees represents East, 90 Represents North, 180 West and 270 South. So from a top down view, it's a counter clockwise system, typical of how you would think of rotations in 2D.
- In NED, A Yaw of 0 degrees represents North, 90 Represents East, 180 South and 270 West. So from a top down view, it's a clockwise system.

To convert a yaw from ENU to NED you would have:
`YawNED = 90 - YawENU` and the same for converting NED to ENU `YawENU = 90 - YawNED`

However for a simple case Quaterion, the identity `(x, y, z, w) = (0, 0, 0, 1)`:
In Unity that would produce an orientation with the forward vector of `(0, 0, 1)`. (East)
When converted to:
ENU: `public Quaternion ConvertFromRUF(Quaternion q) => new Quaternion(q.z, -q.x, q.y, -q.w);`, so the Quaternion becomes `(0, 0, 0, -1)`
Which is still the identity rotation, so the forward vector (ENU) would be `(E, N, U) = (1, 0, 0)`. (East) which is fine.
However for NED:
NED: `public Quaternion ConvertFromRUF(Quaternion q) => new Quaternion(-q.x, q.z, -q.y, -q.w);`, so the Quaternion becomes `(0, 0, 0, -1)`.
Which is also the identity rotation, so the forward vector would also be `(N, E, D) = (1, 0, 0)`. (North) which for NED doesn't make sense since the rotation in Unity faces towards the East. It should be something along the lines of `(0, 0, (√2)/2, (√2)/2)`.

Let me know if this is making sense, I could try make some diagrams of the issue if that would help.

**Comment by peifeng-unity** [comment]
Ah, thank you! I think I got it. After the vector conversions from RUF to NED, the rotation needs to rotate for 90 more degrees (clockwise) with the z-axis (yaw) so that the body could facing to the east for the identity rotation. This makes sense to me. I will create a new PR for it.
