### ISSUE TITLE
Unable to install ros-tcp-visualizer

### ISSUE THREAD

**Issue by fangkd8** [Unity-Technologies/ROS-TCP-Connector#202]
I just follow the tutorial from https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/v0.6.0/com.unity.robotics.visualizations/Documentation~/README.md, but my unity continues reporting errors, just shown in the image. 

![Screenshot from 2021-10-03 07-51-20](https://user-images.githubusercontent.com/43018640/135752367-31ba8f7c-da06-4a38-bc96-6cc00e819b05.png)

How do we solve it? I searched previous issues and ros unity forum but still got nothing.

**Comment by LaurieCheers-unity** [comment]
Hi, you'll need to also install the ROS TCP Connector.

I'll update that doc.

**Comment by fangkd8** [comment]
But before installing visualizer package, I already installed tcp connect with the exact link you shared through package manager

**Comment by LaurieCheers-unity** [comment]
Interesting. What version of Unity are you using? Does your package manager look like this?
![image](https://user-images.githubusercontent.com/73140792/135893632-ff2478ee-48f0-496e-9faf-2340b758d116.png)

**Comment by fangkd8** [comment]
> Interesting. What version of Unity are you using? Does your package manager look like this? ![image](https://user-images.githubusercontent.com/73140792/135893632-ff2478ee-48f0-496e-9faf-2340b758d116.png)

Exactly like this, my unity version is 2020.3.19f1 on ubuntu 18.04.

**Comment by LaurieCheers-unity** [comment]
Strange... I don't have an explanation for these symptoms. Could you provide a copy of your editor log, showing your compile errors? (You can find it by going to the three dots menu at the top right corner of your Console window, and selecting "Open Editor Log".)
