### ISSUE TITLE
ArgumentOutOfRange while deserializing moveit_msgs/DisplayTrajectory message

### ISSUE THREAD

**Issue by Gin-TrungSon** [Unity-Technologies/ROS-TCP-Connector#219]
**Describe the bug**
I sent a moveit_msgs/DisplayTrajectory from ROS2 to Unity but got an Error ArgumentOutOfRangeExeption: Non-negative number required.

Message
```bash
model_id: ur
trajectory:
- joint_trajectory:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: base_link
    joint_names:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    points:
    - positions:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      velocities:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      accelerations:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      effort: []
      time_from_start:
        sec: 0
        nanosec: 0
  multi_dof_joint_trajectory:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: ''
    joint_names: []
    points: []
trajectory_start:
  joint_state:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: base_link
    name:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - finger_joint
    - left_inner_finger_joint
    - left_inner_knuckle_joint
    - right_inner_knuckle_joint
    - right_outer_knuckle_joint
    - right_inner_finger_joint
    position:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    velocity:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    effort: []
  multi_dof_joint_state:
    header:
      stamp:
        sec: 0
        nanosec: 0
      frame_id: base_link
    joint_names: []
    transforms: []
    twist: []
    wrench: []
  attached_collision_objects: []
  is_diff: false
---
```

**Screenshots**
Error
![Screenshot 2021-10-21 134557](https://user-images.githubusercontent.com/52384228/138312383-2ee580e4-b9d7-45b8-8130-41658355ede2.png)

The "length" value is equal 0  while deserializing  /trajectory/multi_dof_joint_trajectory/header/frame_id .
![Screenshot 2021-10-21 134622](https://user-images.githubusercontent.com/52384228/138312419-d44c6e62-ed1b-4610-bcf8-0e9fc6c29cb4.png)

**Environment (please complete the following information, where applicable):**
- Unity Version: Unity 2020.3.13f1
- Unity machine OS + version: Windows 11
- ROS machine OS + version: Ubuntu 20.04, ROS Foxy
- ROS–Unity communication: Docker
- Branch or version: v0.6.0

**Additional context**

Many thanks in advance !

**Comment by Gin-TrungSon** [comment]
Thanks for your help, but i think the main problem is the alignment for zero length arrays.
Please see: https://github.com/eProsima/Fast-CDR/commit/581bc96
I have changed it in my own project and it works.

**Comment by LaurieCheers-unity** [comment]
Hi, thanks for this. The fix has been merged into our dev branch; it will reach main branch next time we make a release.
For now you can use the version in dev branch. https://github.com/Unity-Technologies/ROS-TCP-Connector/tree/dev
