### ISSUE TITLE
Support ROS 2 C# client library

### ISSUE THREAD

**Issue by alsora** [Unity-Technologies/ROS-TCP-Connector#229]
Recently, Robotec AI released a ROS 2 C# client library https://github.com/RobotecAI/ros2cs
The main purpose of this library is to enable easy communication between a Unity simulation and ROS 2 code.
They show an example here https://github.com/RobotecAI/ros2-for-unity

Are you considering supporting this library for ROS 2 rather than the TCP connector?
One of the design principles of ROS 2 was indeed the possibility to easily create client library in a variety of different languages, in order to reduce performance overhead and need for custom solutions.

**Comment by hyounesy** [comment]
Thank you @alsora. We don't have an immediate plan to support ros2cs, but we created an internal ticket to investigate it.
Ticket# [AIRO-1469]
