### ISSUE TITLE
Incorrect step size for Image message in ToImageMsg()

### ISSUE THREAD

**Issue by Macbull** [Unity-Technologies/ROS-TCP-Connector#246]
**Issue and Steps to Reproduce** 
Adding a camera publisher to  unity project from https://github.com/Unity-Technologies/Robotics-Nav2-SLAM-Example using 
`ImageMsg rosImage = mainCameraTexture.ToImageMsg(header);`
causes error while using rqt or image_view node.
`ImageView.callback_image() while trying to convert image from 'rgba8' to 'rgb8' an exception was thrown (Image is wrongly formed: step < width * byte_depth * num_channels  or  4 != 691 * 1 * 4)
`

I think it is due to incorrect size here in this line of code, which just sends step=4 irrespective of width of image.
https://github.com/Unity-Technologies/ROS-TCP-Connector/blob/7f055108f43ab11ff297175a52af5d30fbac9d57/com.unity.robotics.ros-tcp-connector/Runtime/MessageGeneration/MessageExtensions.cs#L747

Problem can be solved by manually assigning step like 
`image_step = 4;`
`img_msg.step = image_step * (uint) frame_width;` 

I will try to reproduce and fix error for different texture types, And open a PR with correct code of `ToImageMsg()`. Although I am not sure if this is specific to ros2 or a general bug.

**Comment by vidurvij-Unity** [comment]
Thank you for brining this to our attention and for your contribution. We will look into this pull request. [AIRO-1648]

**Comment by mrpropellers** [comment]
Closing since fix is now merged into dev
