### ISSUE TITLE
Unable to install ROS-TCP-Connector

### ISSUE THREAD

**Issue by h8476532** [Unity-Technologies/ROS-TCP-Connector#261]
**Describe the bug**
I just follow the tutorial from：https://github.com/Unity-Technologies/ROS-TCP-Connector, want to install the ROS-TCP-Connector and use the Add package from git URL.... to install it, but it jumps out the error, and I also try to add the version like v0.4.0, v0.5.0, v0.6.0, v0.7.0, it still unable to install.
And I use the student version, so I don't know that is the student version can't download by URL or something.

**Screenshots**
![image](https://user-images.githubusercontent.com/88470058/154885800-6fd5f1f2-27b9-4a61-906f-c5ed5365fa1f.png)

**Environment (please complete the following information, where applicable):**
- Unity Version: Unity 2020.2.0f1
- Unity machine OS + version: Windows 10

**Comment by h8476532** [comment]
Already know where is my fault.

**Comment by XiaoLaoDi** [comment]
@h8476532 hi, same problem here, would you mind share how to solve the problem ?
