### ISSUE TITLE
Ros2 Action support

### ISSUE THREAD

**Issue by philipholler** [Unity-Technologies/ROS-TCP-Connector#265]
**Is your feature request related to a problem? Please describe.**
I am currently using both messages and services without any issues. I am, however, unsure of whether TCP-connector supports ROS2 actions. It does say anywhere, that it doesn't. However, i cannot find the methods for using them in the ROSConnection class. I am also able to generate the action cs files from my .action files, so this suggests to me, that actions are supported.

**Describe the solution you'd like**
Action support in the ROSConnection. A way to register for actions with callback on finish and a way to publish on the feedback channel easily.

**Describe alternatives you've considered**
Simply using messages and create a channel for feedback and cancelling and action myself. This would mimic the functionality of actions.

**Additional context**

**Comment by mojervico** [comment]
Are there any advances on this topic?
