### ISSUE TITLE
Ros message generation menu option missing

### ISSUE THREAD

**Issue by francoiscr** [Unity-Technologies/ROS-TCP-Connector#43]
Hi, during the https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/ros_unity_integration/setup.md tutorial,
after adding the https://github.com/Unity-Technologies/ROS-TCP-Connector.git package from git url, the message generation button in menu toolbar is missing.

We are using the Version 2019.4.17f1 (667c8606c536) Personal

We are on Ubuntu 18.04
Using Ros melodic

In the Unity console we have 2 errors

`Library/PackageCache/com.unity.robotics.ros-tcp-connector@457dad63a5/Runtime/ROSGeometry/ROSVector3.cs(202,104): error CS1501: No overload for method 'ToString' takes 2 arguments`

`Library/PackageCache/com.unity.robotics.ros-tcp-connector@457dad63a5/Runtime/ROSGeometry/ROSQuaternion.cs(145,95): error CS1501: No overload for method 'ToString' takes 2 arguments`

There is no error during the catkin_ws compilation

**Comment by LaurieCheers-unity** [comment]
I'm afraid Unity 2019 is not supported, we recommend updating to at least 2020.1.
