### ISSUE TITLE
Are there any plans for HL2 support?

### ISSUE THREAD

**Issue by zaalsabb** [Unity-Technologies/ROS-TCP-Connector#78]
Are there any plans to add UWP support so that we can connect HL2 and ROS using this package?

Thanks!

**Comment by vidurvij-Unity** [comment]
Hi @zaalsabb,
You should be able to use ROS-TCP-Connector on UWP as it is not platform specific. Make sure to follow Unity guide for building UWP apps https://docs.unity3d.com/Manual/windowsstore-buildsettings.html. 
Please feel free to reach out for any further questions.
Vidur

**Comment by peifeng-unity** [comment]
Closing this issue because it is inactive for a while. @zaalsabb Please feel free to reopen it if you have further questions.
